spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/cedb;DB_CLOSE_DELAY=-1;
    username: alekal
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: construction-expenses

logging:
  file:
    name: log/spring-logs.log